### ISSUE TITLE
Add fix for streaming?

### ISSUE THREAD

**Issue by rittet** [homebridge-plugins/homebridge-arlo#10]
As suggested [https://github.com/jeffreydwalter/arlo/issues/7](url) the streamin problem seems to be fixed. Is this something you could add to your homebridge plugin?

**Comment by GatoPharaoh** [comment]
Correct link https://github.com/jeffreydwalter/arlo/issues/7

**Comment by starlessblack** [comment]
I, too, would love to see this implemented in the Homebridge plugin.

**Comment by devarshi** [comment]
hey folks! I just added (preliminary) support for this on my fork of homebridge-camera-ffmpeg using that lib.  
check it out here and feel free to extend : https://github.com/devarshi/homebridge-camera-ffmpeg

**Comment by RSickenberg** [comment]
> hey folks! I just added (preliminary) support for this on my fork of homebridge-camera-ffmpeg using that lib.
> check it out here and feel free to extend : https://github.com/devarshi/homebridge-camera-ffmpeg

No more maintened ... :(
