### ISSUE TITLE
Changing Modes is not working

### ISSUE THREAD

**Issue by CaldenMig21** [homebridge-plugins/homebridge-arlo#119]
I understand that changing security modes (Away, Home, Night or Off) is supposed to change the armed/disarm status of my arlo base station. Somebody knows if this is an expected behavior? Is it working in the arlo plugging?
So far it is great that I can see my arlo cameras in my HomeKit App, I would like to be able to toggle arm/disarm based on some automations...

Thanks

**Comment by Donni1966** [comment]
Hi, this was explain in the documataion. 

Go to the web Interface and generate a state for 
night
day 
at home.

after generation right side is an arrow
![Bildschirmfoto 2021-02-26 um 22 05 29](https://user-images.githubusercontent.com/61660957/109355040-efd72980-787e-11eb-9752-09d6c678b7bb.png)

Block on it you geht in the browser address line the mode ... 
![Bildschirmfoto 2021-02-26 um 22 07 30](https://user-images.githubusercontent.com/61660957/109355229-39c00f80-787f-11eb-8dc1-f5f496d00449.png)

in the config.json do like this 
{
    "streaming": {
        "videoDecoder": "h264_mmal",
        "packetSize": 564,
        "videoEncoder": "h264_omx"
    },
    "name": "Arlo",
    **"night_arm": "mode2",**
    "email": "xvcxcvcxvcvcvcvx",
    **"stay_arm": "mode1",**
    "interval": 6000,
    "password": "vxbcgdgfgffd",
    "platform": "Arlo",
    "_bridge": {
        "username": "0E:1C:AF:6B:B5:D7",
        "port": 34870
    }
}

i use only night an stay_arm ... 

byby, Michael

**Comment by CaldenMig21** [comment]
Thanks Michael...
I tried all your recommendations: 
- I created several modes in the arlo web app: Night : Mode2, Day: Mode 3, at home: Mode 4 (even if ai an not using some of these modes)
- Here is the Hoobs generated Config.json:

 {
            "platform": "Arlo",
            "plugin_map": {
                "plugin_name": "homebridge-arlo"
            },
            "name": "Arlo",
            "include_cameras": true,
            "email": "xxx@gmail.com",
            "password": "yyyyyy",
            "streaming": {
                "videoProcessor": "ffmpeg",
                "videoDecoder": "libx264",
                "videoEncoder": "libx264",
                "audioEncoder": "libopus",
                "packetSize": "564",
                "maxBitrate": "300"
            },
            "stay_arm": "mode1",
            "night_arm": "mode2",
            "interval": 6000
        },

When I toggle in the home app the Base station securirty switch. This is the behavior:
- If I set it on "Night", it sais: "arming" and toggle back to "Away", nothing happens on Arlo
- If I set it on "Home", It keeps saying "arming" and nothing happens on Arlo
- If I set it on "Away", It just changes without saying anything and nothing happen on Arlo
- If I set it on "Off", It sais: Disarming, but nothing happens on Arlo app.

Am I missing something in the Configuration?, I do not see any bridge with User Name or Port, in the Hoobs generated config json.

Thanks againg for the support!!! 
Miguel

**Comment by Donni1966** [comment]
Hi

Looks fine. I forgot 1 thing. Do you create a separate account for hoobs?! 

And I use no hoobs 


MfG 
       Michael Schröder
       Per Mail:      
       Mi_Schroeder@web.de 
       Per Handy:
       +49 170 8165321

**Comment by sanstarr** [comment]
One Question:
How do you manage to get the Arlo plugin functional without 2fa?

Thanks!

**Comment by Donni1966** [comment]
I do not know why it works, but i think, the reason is, that i have create a account second Account for my Homebridge. i use this, make the 2fa with my iphone, and after this, hie never ask me again. 

it is really more than useful to create this 2. Account.  If you have only one - this will not work. 


Mit freundlichen Grüßen
      Michael Schröder
Tja, Proton müsste man sein; man würde die Quantenphysik verstehen, wäre immer positiv drauf, und hätte eine nahezu unbegrenzte Lebenszeit. 
(Silvia Arroyo Camejo)
