### ISSUE TITLE
Can't get stay_arm or night_arm modes to work

### ISSUE THREAD

**Issue by Djelibeybi** [homebridge-plugins/homebridge-arlo#12]
I'm not sure if this is a bug, a change in the Arlo API or user error, but I can't seem to get either of the `stay_arm` or `night_arm` modes to trigger via HomeKit. 

I can see via the debug logs that `homebridge-arlo` is sending the right mode name (`Night`) and it seems to get a `success: true` response::

```
Arlo { url: 'https://arlo.netgear.com/hmsweb/users/devices/notify/[REDACTED]',
Feb 10 15:14:42 homebridge homebridge[31492]:   method: 'POST',
Feb 10 15:14:42 homebridge homebridge[31492]:   body:
Feb 10 15:14:42 homebridge homebridge[31492]:    { action: 'set',
Feb 10 15:14:42 homebridge homebridge[31492]:      resource: 'modes',
Feb 10 15:14:42 homebridge homebridge[31492]:      publishResponse: true,
Feb 10 15:14:42 homebridge homebridge[31492]:      properties: { active: 'Night' },
Feb 10 15:14:42 homebridge homebridge[31492]:      from: '[REDACTED]',
Feb 10 15:14:42 homebridge homebridge[31492]:      to: '[REDACTED]' },
Feb 10 15:14:42 homebridge homebridge[31492]:   json: true,
Feb 10 15:14:42 homebridge homebridge[31492]:   jar: true,
Feb 10 15:14:42 homebridge homebridge[31492]:   headers:
Feb 10 15:14:42 homebridge homebridge[31492]:    { xCloudId: '[REDACTED]',
Feb 10 15:14:42 homebridge homebridge[31492]:      'User-Agent': 'request',
Feb 10 15:14:42 homebridge homebridge[31492]:      Authorization: '[REDACTED]' } }
Feb 10 15:14:43 homebridge homebridge[31492]: 2018-02-10T15:14:43.890Z Arlo { success: true }
```

Interestingly, Home reports that "Arlo was armed for night" or "Arlo was armed for stay", but it actually just switches to "Armed" in both cases when I check in the Arlo app, not the custom "Home" or "Night" modes I've configured.

**Comment by devbobo** [comment]
@Djelibeybi the value for `active` needs to be in the format `modeX` where `X` is a given number of the Mode.

For example, `mode0` === `Disarmed`, `mode1` === `Armed`. Typically, the first custom mode receives `mode2` as it's identifier.

It should be easy enough to work out which is which by trial and error. Or you could try looking in the network requests on the arlo set when setting a specific mode as active...
![arlo_smart_home_security_cameras___home_monitoring___arlo_by_netgear](https://user-images.githubusercontent.com/680871/36069523-927036ac-0f3f-11e8-9b62-6463704631c9.png)

**Comment by Djelibeybi** [comment]
That makes perfect sense. I just submitted PR #13 to update `README.md` to make it clearer in the docs too.

**Comment by devbobo** [comment]
Thanks
