### ISSUE TITLE
Siri commands not working remotely

### ISSUE THREAD

**Issue by Djelibeybi** [homebridge-plugins/homebridge-arlo#14]
I'm currently overseas and noticed that Siri won't control Arlo remotely (out of the house). If I try the documented phrases, here's how she responds: "**Sorry, I can't control your Home Security System.**"

Also, I can't get her to even think about switching to **night** mode because she always hears  "tonight" instead of "to night" which confuses the poor thing.

If someone can confirm whether the commands work inside the house, I'm happy to update the `README.md` to document the restriction about using Siri at home vs away from home.

**Comment by devbobo** [comment]
@Djelibeybi Apple removed the ability to set the Home Security System states directly via Siri. The best way to achieve this now is to use `Scenes`. I typically use `Good night`, `I'm leaving` and `I'm home` to set the states I require.

**Comment by Djelibeybi** [comment]
@devbobo that's what I figured. 

To restore functionality with geolocation I created a `homebridge-dummy` switch which turns on/off as the last person leaves and the first person arrives. I have a separate automation that arms/disarms Arlo based on the state of that switch.

I'll write both options up and submit a PR later.
