### ISSUE TITLE
No base but three movement sensors

### ISSUE THREAD

**Issue by Travis-DK** [homebridge-plugins/homebridge-arlo#17]
After installing and updating, editing the config.json, I search for new accessories in the home app.
The base doesn't show up, but all three cameras. I can only add one of them though. And when I do it shows up in the app as a movement sensor, which by the way doesn't react to any movement (yes, I've been dancing in front of all three).

What am I doing wrong?

**Comment by Travis-DK** [comment]
Ok... This is a little embarrassing. Managed to solve the issue by myself. To anyone else having this issue: remember to grant admin rights to the additional user you create for home kit access

**Comment by ChristianPorsche** [comment]
Does giving admin rights also solve the motion notifications for you?
