### ISSUE TITLE
Work with Arlo Q?

### ISSUE THREAD

**Issue by CarterBrehm** [homebridge-plugins/homebridge-arlo#19]
I have two Arlo Q's that I can help test with if needed. All I can access right now is my basestation, which doesn't really help much.

**Comment by jazzphone** [comment]
Same here.  Doesn't seem to find the Arlo Q.

You can use IFTTT and Homebridge to achieve a similar result with the Q, however IFTTT doesn't support any custom modes.

This isn't as big of a deal when the Arlo Q acts as a Single Camera/Base Station in the App.

**Comment by yenoromm** [comment]
Just an FYI, I have been using this plugin with for a while with my 3X Pro 2's which shows as expected and an Arlo Q which didn't show up. Bought an Arlo Q Plus (using with WiFi not poe/ethernet) as it worked out cheaper than a Q with Black Friday sales. The Q Plus works with this plugin, screenshot, motion trigger and another 'Alarm' showed up.

Edit: At this point cannot work out how to configure Home and Night.
