### ISSUE TITLE
Snapshot is only working for a special period of time

### ISSUE THREAD

**Issue by Phoenix-DH** [homebridge-plugins/homebridge-arlo#20]
Hi,

I have installed the normal devbobo/homebridge-arlo branch release.
I added the cameras nto homekit, I have 2 available.
After starting the homebridge service, the snapshot are working some times fpr 2, the other time only for one hour.
AFter that is is stopping.

In the homebridge log, there is no error.
You can see the following line:
[arlo] snapshot request: Camera XXX

But no snapshot is created.
In the log there will be no other entries ...
No skipping, no downloading ...

Is this known? Do I have to use another branch?
An actual snapshot will be enough for me, I need no live video.

**Comment by michaelkedwards** [comment]
I'm seeing the same problem and would also love to know what I can do if someone knows.

**Comment by Phoenix-DH** [comment]
Any hints?

**Comment by Phoenix-DH** [comment]
In this conversation I only talk about the plain installation of devbobo/homebridge-arlo
No other additions, for me it would be enough to have a static working picture all X minutes.

@devbobo : Maybe you can give some information if this is a known bug or if something is missing.

Thank you!

**Comment by 5and0** [comment]
I am also seeing this exact issue. Running Homebridge on a raspberry pi.

**Comment by ChristianPorsche** [comment]
Same problem. Running homebridge on mac
