### ISSUE TITLE
Possible to use alarm trigger in Homekit.

### ISSUE THREAD

**Issue by ftonat** [homebridge-plugins/homebridge-arlo#24]
Hi,
Arm and disarm is working fine in my setup. 
I use scenes to change the state. 

Next I want to act on an movement within camera ranges if armed. 

Is there a way to use a trigger in Homekit?
If not, any hints, eg IFTTT or any other homebridge plugins?

Frank

**Comment by Phoenix-DH** [comment]
I think there is no possibility because this is not implemented in ARLO api.
I am searching for the same.

If something is happening that has nothing to do with ARLO, as example opening a door with eve sensor, start siren ...

No way found until now.

**Comment by ftonat** [comment]
Hi Phoenix-DH, are you aware of the publication system of the ARLO API?
I have seen the following description:

> EVENT PUBLICATION AND SUBSCRIPTION
> Arlo system uses a pub/sub messaging system leveraging the EventStream browser interface. In few words, the browser/application opens a channel (makes a subscription) where the server dispatches events (such as mode changes, alerts, etc.). This is useful for getting real time updates, but it is not strictly required to perform operations such arming/disarming system.
> 
> Events could be spontaneously issued by the server or initiated by a client, Arlo uses two end points for such operations:
> 
> https://arlo.netgear.com/hmsweb/client/subscribe
> and
> 
> https://arlo.netgear.com/hmsweb/users/devices/notify
 
Please refer to: [https://www.robertogallea.com/blog/netgear-arlo-api](https://www.robertogallea.com/blog/netgear-arlo-api)

Frank

**Comment by Phoenix-DH** [comment]
Hi,

no I am not ... that was what me told innother discussion boards.

I would be really great if this would be possible.

**Comment by Phoenix-DH** [comment]
Any news on that?

Is there a possibility to start the siren when for example a third party sensor is detecting something?
