### ISSUE TITLE
Arlo Baby recognised as "sensor" in HomeKit

### ISSUE THREAD

**Issue by jeremyhiggs** [homebridge-plugins/homebridge-arlo#26]
I've installed homebridge-arlo and manually added an Arlo Baby into HomeKit. I'm not expecting the camera to work, but for some reason it's recognised by HomeKit as a sensor. As a result, I can't arm/disarm it. Is it simply a matter of homebridge-arlo not recognising the model, and adding support? Or is there something else that I'm missing?

**Comment by wiiiimm** [comment]
Arlo Baby by default comes with a Homekit camera, and 4 Homekit sensors (temperature, humidity, air quality, motion sensor). Maybe you are seeing those?

**Comment by jeremyhiggs** [comment]
This was actually before the Arlo Baby had HomeKit integration (IIRC).

**Comment by williamli** [comment]
@jeremyhiggs side question, do you need to have an Arlo base station at home to use this plugin? I am trying to get HomeKit to toggle the state of my Arlo Baby

**Comment by williamli** [comment]
@jeremyhiggs it seems this plugin only works with the Arlo basestation and according to Arlo's FAQ:

> Note: Arlo Baby connects directly to your WiFi network. You cannot connect Arlo Baby to an Arlo base station or another Arlo camera.
