### ISSUE TITLE
Can't set mode to Night/Home

### ISSUE THREAD

**Issue by yoeduardoj** [homebridge-plugins/homebridge-arlo#28]
I've configured modes correctly, mapping home_arm to mode2 and night_arm to mode3, and the homebridge user is correct. From what I see, the request to set the mode succeeds, I get a notification telling me it was changed, and then quickly the mode gets modified to the default mode.

The request made looks like:
`Arlo:REST {"url":"https://arlo.netgear.com/hmsweb/users/devices/notify/<redacted>","method":"POST","body":{"action":"set","resource":"modes","publishResponse":true,"properties":{"active":"mode3"},"from":"<redacted>","to":"<redacted>"},"json":true,"jar":true,"headers":{"xCloudId":"<redacted>","User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS <redacted> like Mac OS X) AppleWebKit/<redacted>(KHTML, like Gecko) Mobile/<redacted> NETGEAR/v1 (iOS Vuezone)","Authorization":"<redacted>"}}`

You can see `mode3` was selected, which is correct as I mapped it.

The response is simple:

`Arlo:REST {"success":true}`

After that, I observe the following log repeats a bit for a number of devices.

EventedHTTPServer [<redacted>] Sending HTTP event '4.11' with data: {"characteristics":[{"aid":4,"iid":11,"value":2}]}

I then see the following:

```EventedHTTPServer [::ffff:10.0.0.10] Muting event '4.11' notification for this connection since it originated here.
EventedHTTPServer [::ffff:10.0.0.3] Sending HTTP event '4.10' with data: {"characteristics":[{"aid":4,"iid":10,"value":1}]}
```

^^ that value:1 seems suspicious.

My config is super-simple:
```
{
                "platform": "Arlo",
                "name": "Arlo",
                "email": "<redacted>",
                "password": "<redacted>",
                "stay_arm": "mode2",
                "night_arm": "mode3",
                "interval": "6000"
        }
```

I have the latest version of everything. I've changed all the calls to `debugComm` locally to call `JSON.stringify` in order to properly print the entire body, otherwise arrays get printed as `[Array]`.

**Comment by lordofthegins** [comment]
On my setup, I've got stay_arm as mode0 which is by default the disarmed state and labelled as "home" in Home app. (Same as 'Off' in Home App). Unless you want some cameras recording while you're home, that should work?
