### ISSUE TITLE
No notifications of state/mode changes

### ISSUE THREAD

**Issue by frli4797** [homebridge-plugins/homebridge-arlo#30]
When I change the mode/state of my Arlo outside homebridge, for instance using the Arlo App, the change doesn't seems to be detected by Arlo Homebridge. However on changing the state in Homekit app, all notifications seems to be working.

config.json snippet
`"platforms": [
        {
            "email": "email@address.com",
            "password": "s33cret",
            "platform": "Arlo",
            "interval": 3000,
            "stay_arm": "mode3",
            "night_arm": "mode2",
            "name": "Arlo"
        },
        {
            "error_log": "/var/log/homebridge.stderr.log",
            "log": "/var/log/homebridge.stdout.log",
            "platform": "config",
            "port": 1234,
            "restart": "/usr/local/bin/supervisorctl restart homebridge",
            "name": "Config"
        }
    ]
`

**Comment by CooperCGN** [comment]
The plugin doesn't work bi-directional, it can set the state of the system e.g. armed, home, etc. but it is not polling the state so if you make any changes outside HomeKit it won't change in HomeKit.
