### ISSUE TITLE
Plugin does not arm the camera anymore

### ISSUE THREAD

**Issue by robpegurri** [homebridge-plugins/homebridge-arlo#32]
Good morning, this is serious.

It seems the plugin does not activate the cameras anymore. I tried changing the password and re-installing the plugin. 

Can anybody confirm?
Thanks

**Comment by magnusaurus** [comment]
Yes, i have the same issue!

**Comment by magnusaurus** [comment]
> 
> 
> Yes, i have the same issue!

Okay it worked after a update 👍
