### ISSUE TITLE
ARLO now with native Homekit support

### ISSUE THREAD

**Issue by Phoenix-DH** [homebridge-plugins/homebridge-arlo#34]
Hey,

since this week there is a native homekit support from ARLO available.
I had the chance to have a look to a friends of mine config.
Stupid thing is that there will be no security system with this 4 several settings present, only the cams and the motion sensor.
Live view, integrated pushes is fine working.

I know this is also availabble in the plugin, but this never worked for me.

When I have a look into ARLO it finds automatically the security system expanded from this plugin, but nothing more.
Having a look to homekit itself, I see the base, but cannot add it because I do not know the pin.

Had anybode else get it worked in a combination?

**Comment by mbial** [comment]
I dont seem to be able to get this working.  I was already using the native Arlo HomeKit integration to access the video streams of each camera.  The home bridge logs don't show much, but nothing appears in the Home app.  My hope was to be able to arm and disarm them using this plugin.  Any advice?
