### ISSUE TITLE
Simply won't show up in Homekit 

### ISSUE THREAD

**Issue by Big-IoT-Man** [homebridge-plugins/homebridge-arlo#37]
hi there, so I've followed the instructions for the basic install to try and get my Arlo ultra hub onto the Homekit app however it doesn't show up at all. I'm not sure if this is because the ultra is now natively compatible or because I have 2 factor auth. but anyways id still like to use the plugin to be able to arm and disarm the Arlo cameras from the home app as this can't be done even with the current Arlo support.

**Comment by felipeazucares** [comment]
Hi late response I know, but have you tried disabling 2FA?
