### ISSUE TITLE
2FA support mandated

### ISSUE THREAD

**Issue by HumanSkunk** [homebridge-plugins/homebridge-arlo#38]
Received an email saying that 2FA would be a requirement by the end of the year. Is there any plan (I know it hasn’t been updated in a while) to update this to include this else this plugin will no longer work beyond that date. I have the original base station and use it as a reliable way to activate and deactivate the system through Apple Home.

I know I could look at adding it, but have 0 coding experience and totally dependent on other more skilled people than myself for this functionality.

Thanks

**Comment by Phoenix-DH** [comment]
Also my question! Thanks for answering.

**Comment by CooperCGN** [comment]
I have the bad feeling that this plugin isn’t maintained anymore...

**Comment by Phoenix-DH** [comment]
Yeah, bad ....
Great plugin because you have a whole security system is in home and you can use the internal automatism.
NAtive ARLO home support does only provide tha cams.

**Comment by HumanSkunk** [comment]
Indeed. I have more trust in the home app switching the security states rather than relying on the Arlo app geofencing which I could not get to reliably to work. Fingers crossed that there could be some update before 2FA is forced, else I will have to look at finding an alternative solution.

**Comment by Phoenix-DH** [comment]
I use it in so many scenarios ...
Not possible in ARLO app...

**Comment by starlessblack** [comment]
Yeah, the prognosis doesn't look good for this plugin unless someone picks it up and brings it up to date. At the moment, my plan is to unfortunately ad complexity by utilizing IFTTT webhooks to arm and disarm the Arlo base station :-/

**Comment by Phoenix-DH** [comment]
Have no clue about that kind of programming 🤷🏼‍♂️

**Comment by CooperCGN** [comment]
I am using this plugin now
https://github.com/MiguelRipoll23/homebridge-securitysystem
with IFTTT webhoooks. Works quite well although I would prefer a non IFTTT way.

**Comment by HumanSkunk** [comment]
> I am using this plugin now
> https://github.com/MiguelRipoll23/homebridge-securitysystem
> with IFTTT webhoooks. Works quite well although I would prefer a non IFTTT way.

Silly question but if you are using web hooks won’t that all break when Arlo introduces 2FA? How do you have it configured?

**Comment by CooperCGN** [comment]
No idea, I guess Arlo has to update their login to ifttt
