### ISSUE TITLE
Avoid camera discovery

### ISSUE THREAD

**Issue by vzlgdu** [homebridge-plugins/homebridge-arlo#39]
Hi, I would understand if is it possible avoid discovery of camers: after homebridge startup I receive the following message:

[Arlo] Found: Camera - xxxxx [xxxxxxxx]

but  I need only commands for base station (already available). Moreover I don't want to see all cameras available in Homekit when I add new device.
Is there a flag to avoid this?

Thanks

**Comment by black01gt** [comment]
I would like to see the same.

**Comment by mbial** [comment]
Also agree

**Comment by donavanbecker** [comment]
@vzlgdu we have added this support in the `latest` version.
