### ISSUE TITLE
Arlo account

### ISSUE THREAD

**Issue by CooperCGN** [homebridge-plugins/homebridge-arlo#4]
Does the homebridge account keep logged in, if i set Arlo to away in the Arlo app the status for some time keeps being reflected back to homebridge, after a while this stops until the next restart of homebridge.

**Comment by devbobo** [comment]
Are homebridge and arlo using the same account ? In the instructions in the README.md, I highly recommend creating a specific arlo account just for homebridge.

**Comment by CooperCGN** [comment]
I created a separate account which I then invited to my arlo, that account is not used anywhere else. My main account is my .mac email address and my 'homebridge' account is my .icloud email. It keeps working for some time if I use the arlo app and even switch from my iPhone to my iPad, so it can't be that. It's almost as if the homebridge account at some point gets kicked from the arlo servers.

**Comment by Locutus73** [comment]
Same here
