### ISSUE TITLE
2.1.0 stopping homebridge

### ISSUE THREAD

**Issue by solarbeat** [homebridge-plugins/homebridge-arlo#57]
**Describe The Bug:**
Updated to 2.1.0 and now Homebridge (1.1.0 or 1.1.1) won't start. Using Arlo Pro cameras. Homebridge never successfully starts, keeps trying. Removing the homebridge-arlo plugin/config allows Homebridge to start. No issues previous to upgrade.

**To Reproduce:**
Using Homebridge 1.1.0 or 1.1.1, set up homebridge-arlo 2.1.0

**Expected behavior:**
Expected behavior is successful Homebridge startup while using the plugin.

**Logs:**
config.json contains this:
        {
            "platform": "Arlo",
            "name": "Arlo",
            "email": "myaccountusedfortheplugin",
            "password": "mypassword",
            "stay_arm": "mode2",
            "interval": 6000
        },

> [6/17/2020, 10:18:20 AM] TypeError: Cannot read property 'videoProcessor' of undefined
>     at new ArloCameraSource (/usr/local/lib/node_modules/homebridge-arlo/ArloCameraSource.js:26:38)
>     at ArloPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-arlo/index.js:94:45)
>     at ArloPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/index.js:147:26)
>     at Arlo.emit (events.js:311:20)
>     at Arlo.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
>     at Request._callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
>     at Request.self.callback (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:311:20)
>     at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:1154:10)
>     at Request.emit (events.js:311:20)
>     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-arlo/node_modules/request/request.js:1076:12)
>     at Object.onceWrapper (events.js:417:28)
>     at IncomingMessage.emit (events.js:323:22)
>     at endReadableNT (_stream_readable.js:1204:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by donavanbecker** [comment]
please use issue template.

**Comment by solarbeat** [comment]
updated, thanks.

**Comment by donavanbecker** [comment]
Can you set the video processor to `ffmpeg`. And then restart homebridge.

**Comment by solarbeat** [comment]
That did the trick. Explicitly set the video processor to ffmpeg, which resolved the issue. Thank you.
