### ISSUE TITLE
Error starting plugin: cannot read property 'videoProcessor' of type undefined

### ISSUE THREAD

**Issue by starlessblack** [homebridge-plugins/homebridge-arlo#59]
**Describe The Bug:**
This seems to be the same/similar bug as described here: https://github.com/homebridge-plugins/homebridge-arlo/issues/57#issue-640613855
I tried to add the property `"videoProcessor": "ffmpeg"` to the config.json, but that didn't help either. I don't use the cameras for streaming through Homebridge, only use it for setting armed/disarmed state of Arlo.

**To Reproduce:**
I upgraded the homebridge-Arlo plugin from 0.0.3 to 2.0.1. Restarted homebridge, it crashed out and will not stay running.

**Expected behavior:**
I expected it to load the new plugin without crashing.

**Logs:**
```
 [6/27/2020, 4:21:46 PM] TypeError: Cannot read property 'videoProcessor' of undefined
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at new ArloCameraSource (/usr/lib/node_modules/homebridge-arlo/ArloCameraSource.js:26:38)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at ArloPlatform.addAccessory (/usr/lib/node_modules/homebridge-arlo/index.js:94:45)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at ArloPlatform.<anonymous> (/usr/lib/node_modules/homebridge-arlo/index.js:147:26)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Arlo.emit (events.js:315:20)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Arlo.<anonymous> (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Request._callback (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Request.self.callback (/usr/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Request.emit (events.js:315:20)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-arlo/node_modules/request/request.js:1154:10)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Request.emit (events.js:315:20)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-arlo/node_modules/request/request.js:1076:12)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at Object.onceWrapper (events.js:421:28)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at IncomingMessage.emit (events.js:327:22)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at endReadableNT (_stream_readable.js:1221:12)
Jun 27 16:21:46 raspberrypi homebridge[22829]:     at processTicksAndRejections (internal/process/task_queues.js:84:21) ```

**Homebridge Config:**

```json
"platform": "Arlo",
"name": "Arlo",
"email": "myusername",
"password": "mypassword",
"stay_arm": "mode2",
"night_arm": "mode3",
"interval": 3000,
"videoProcessor": "ffmpeg"
}, ```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.18.0
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.1.1
* **Homebridge Config UI X Plugin Version**: NOT USING THIS PLUGIN
* **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
`include_cameras`: Defaults to `true`. If you do not want to include the cameras, this can be set to `false`.

**Comment by starlessblack** [comment]
> `include_cameras`: Defaults to `true`. If you do not want to include the cameras, this can be set to `false`.

Thank you. So will setting the cameras to disabled prevent it from searching for the video processor and ffmpeg and whatever else it appears to be getting hung up with when it tries to start?

**Comment by starlessblack** [comment]
I'd still to know the arc of this problem, but for now I've been able to get the plugin (and Homebridge) started again by adding the `include_cameras: "true"` string to my config.json. I didn't see it documented anywhere and was sure if it was supposed to go in the new `streaming: {` properties array, but this page seemed to indicate it would just go along with the other properties: https://github.com/homebridge-plugins/homebridge-arlo/blob/master/config.schema.json

**Comment by donavanbecker** [comment]
If you use config ui x, it make it easy for you to know where it goes. Also config is on the wiki of the repo.

**Comment by starlessblack** [comment]
Yeah, I haven't gotten around to installing/configuring UI X yet. I don't see anywhere in the wiki where it specifies where to put the `include_cameras` property. Anyway, changed it back to "true" and then explicitly added the "videoProcessor" property in the "streaming" array like this:
`"streaming": {
                "videoProcessor": "ffmpeg"
                     }`
Now Homebridge starts up just fine, but I don't see any camera accessories available to add in my Home app. Isn't that how they're supposed to show up?

**Comment by MattR2424** [comment]
You need to explicitly type in ffmeg into settings (not json). Then it should work.

**Comment by julianschmuckli** [comment]
I have just added the ffmpeg attribute in the streaming settings, and it seems to work:
![image](https://user-images.githubusercontent.com/6286544/100488843-deac3e80-3110-11eb-935a-0b300bc650b6.png)
