### ISSUE TITLE
Should the basestation be treated as a security system?

### ISSUE THREAD

**Issue by cmsj** [homebridge-plugins/homebridge-arlo#6]
The 4-states vs 2-states thing is a bit weird, but most unhelpfully, HomeKit does not allow presence events to automatically trigger state changes in security systems.

I wanted to set up HomeKit automations such that if I go out during the day, the Arlo will be armed, but because it's a security system, HomeKit requires me to confirm the state change manually on my phone, which makes the automation pretty useless. It can be worked around with an additional HomeKit device that triggers the Arlo, but I can't help but wonder if it might just be easier/better to have homebridge-arlo register the base station as a simple switch.

**Comment by devbobo** [comment]
Have you tried using the `Geofencing` option within the `Arlo` app ? Setting this up, should enable/disable the system as you require and HomeKit will be updated accordingly.

**Comment by sdorilas** [comment]
Have you been able to arm/disarm using Siri? I always get an error she cannot control it but it appears to work fine otherwise.

**Comment by devbobo** [comment]
@sdorilas hmm...I hadn't tried this since upgrading to iOS11, it appears to be no longer working :(

Personally, I have all my arm/disarm actions tried to common scenes like "Goodnight", "Good Morning", "I'm Leaving" and "I'm Home"

**Comment by cmsj** [comment]
@devbobo I haven't tried that, I just set up a geofence in the Home app directly.

**Comment by mcj** [comment]
@cmsj @sdorilas I made HomeKit scenes called "Arlo On" and "Arlo Off", with just the Arlo accessory selected, in the obvious states.  Siri seems to be able to set those scenes without trouble.
