### ISSUE TITLE
Scheduled state  

### ISSUE THREAD

**Issue by Joeviking** [homebridge-plugins/homebridge-arlo#60]
**Is your feature request related to a problem? Please describe.**
Need a state to set the arlo to Scheduled Mode in arlo interface modes

**Describe the solution you'd like**
Change Homebridge Night mode to use the Scheduled mode 

**Describe alternatives you've considered**
Away and off can be used for arm and disarm

**Additional context**
And Away can be used for custom modeX modes that was created in Arlo Modes

        {
            "name": "Arlo",
            "email": "joe.vikings@gmail.com",
            "password": "Nianta1991",
            "Away": "Schedule",
            "off": "mode0",                              (( Or Mode X)) to disarm
            "streaming": {
                "videoDecoder": "h264_mmal",
                "videoEncoder": "h264_omx",
                "packetSize": 564
            },
            "platform": "Arlo"
        }
    ]
}

**Comment by starlessblack** [comment]
You need to change your Arlo password.

**Comment by starlessblack** [comment]
>
>  "**email": "joe.vikings@gmail.com",
>         "password": "Nianta1991",**
>  

You need to change your Arlo password.

**Comment by Joeviking** [comment]
> > "**email": "[joe.vikings@gmail.com](mailto:joe.vikings@gmail.com)",
> > "password": "Nianta1991",**
> 
> You need to change your Arlo password.

No stress 😎 was blind lol 😂. Tnx for the heads up
