### ISSUE TITLE
Video streaming seems to work, audio does not

### ISSUE THREAD

**Issue by starlessblack** [homebridge-plugins/homebridge-arlo#61]
**Describe Your Problem:**
I am trying to get audio transcoding/streaming working. It would _appear_ that 2.1.0 build of this plugin also install the ffmpeg-for-homebridge plugin depedency (https://github.com/homebridge/ffmpeg-for-homebridge), which I guess has some preconfigured settings for Homebridge installs. So based on the information on that page, I'm guessing it installed ffmpeg with libfdk-aac audio transcoder? I don't really know enough about ffmpeg to verify this. That said, the Arlo plugin documentation refers to both "libfdk_aac" and "libfdk-aac" so I've tried both my config.json, but neither seem to work.

When I launch the live feed of the camera, the video stream connects and properly updates, and the audio channel takes over on the iOS device (e.g. if some music is playing, it's properly faded out, in anticipation of audio feed from Home app), but it just plays silence/dead air.

EDITED: Also, I noticed in the homebridge-arlo documentation this bit: "Defaults to the libopus codec, and currently Homebridge-Arlo tells HomeKit it only supports the Opus audio type." If that information is still accurate--that the plugin tells HomeKit it only supports Opus audio type--then does that mean that making any change to to the audioEncoder would have no effect anyway?

**Logs:**
No pertinent logs that I can think of. There are no errors that I've found.
**Homebridge Config:**

```
"streaming": {
                "videoProcessor": "ffmpeg",
                "audioEncoder": "libopus" (have also tried "libfdk-aac" and "libfdk_aac")
                     }
```

**Screenshots:**
N/A

**Environment:**

* **Node.js Version**: 12.18.1
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.1
* **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
pull requests are welcome.

**Comment by starlessblack** [comment]
Does anyone have streaming working? Working with both video and audio? At this point, I don't even know if it's possible, so I'm not sure I should continue fiddling with config.json streaming parameters or what. I installed the ffmpeg-for-homebridge package, and now I'm pretty darn certain I have the proper libfdk_aac and other codecs, and it still doesn't work for audio.

Also, when I change the "streaming": properties in the config.json to use libx264 or h264_mmal or _omx codecs, I'm not seeing any significant difference in CPU usage for the ffmpeg process in top while streaming a vid. This kind of leads me to think the "streaming": parameters in the config.json aren't being respected or aren't really doing anything.

Have you seen this behavior?

**Comment by fkick** [comment]
Are you actually seeing Arlo cameras showing up in HomeKit? Per the wiki, this plugin only supports the basestation. If you are seeing cameras, I would love to know how you got those to appear.

**Comment by starlessblack** [comment]
Yes, the cameras show up in HomeKit. In fact, this behavior has not changed in any way I can tell since homebridge-arlo ver. 0.0.3 when the plugin was maintained by someone else. What works better now (likely because I have the ffmpeg-for-homebridge package installed) is the actual video streaming. On 0.0.3, if memory serves, the video streaming would often not start or dropped frames/stuttered if it did start.

I just assumed you had to add the basestation via the this plugin, and then the basestation was what brokered the TCP connections to Homebridge and then off to Home app. ::shrugs::

I don't get the feeling anyone quite knows the ins and outs of this plugin fully. Certainly not me :)

**Comment by MattR2424** [comment]
This thread allowed me to fix video (hint: installing ffmpeg support on your machine is key). However - I'm in the same boat with audio.
