### ISSUE TITLE
Snapshots, Video?!

### ISSUE THREAD

**Issue by FutureGUIs** [homebridge-plugins/homebridge-arlo#8]
I really appreciate your work getting the arlo camera's working.  I know you're probably not done with the feature by any stretch, but I'm here to help if you need it.

Right now, the snapshots seem to be almost fully stable, it doesn't always get an update though, and clicking on a camera from Apple Home tries to get a fresh snapshot, but that seems to fail, and the video doesn't seem to work either, it says 'prepareStream' and then 'handleStreamRequest', and in Home it says 'No Response.  Again, sorry if I'm jumping the gun on this, but I'm excited for this development.

**Comment by devbobo** [comment]
@FutureGUIs there is still some work to do to make `snapshots` more stable, the asynchronous nature of requesting and retrieving snapshots makes it difficult to respond to HomeKit in a timely manner in some cases.

Video streams is going to be more difficult as the streams from Arlo aren't in the correct format to stream directly to HomeKit. Therefore, the stream will need to be run to FFMPEG to transcode to the correct video format (I forget the specs).

I will probably tinker with the snapshot functionality over my xmas break. But at this point, I'm not sure when I will get to streaming.

**Comment by paulofierro** [comment]
As someone who would love this functionality, [I found this thread on integrating with Nest cams](https://github.com/KraigM/homebridge-nest/issues/68#thread-subscription-status). These also stream in a different format.

In case it helps 🤞

**Comment by Djelibeybi** [comment]
Where exactly are you supposed to be able to get snapshots from the Home app? I can see my Arlo, but I don't see any cameras.

**Comment by devarshi** [comment]
so, I got Arlo (pro 2) integrated and working with homebridge-camera-ffmpeg. Just video streaming + snapshots for now, but it's a start. 
https://github.com/devarshi/homebridge-camera-ffmpeg

**Comment by meesjan** [comment]
> so, I got Arlo (pro 2) integrated and working with homebridge-camera-ffmpeg. Just video streaming + snapshots for now, but it's a start.
> https://github.com/devarshi/homebridge-camera-ffmpeg

Could you please post your config.json?

**Comment by cbpowell** [comment]
I also recently submitted a PR to support streaming (heavily based on FFmpeg too), it's pending incorporation into the main branch - you can check it out on the [streaming-pr branch](https://github.com/devbobo/homebridge-arlo/tree/streaming-pr) or on [my fork](https://github.com/cbpowell/homebridge-arlo).

More testing always helps if you guys want to try it out! You do need a fairly specific FFmpeg if you're using a Raspberry Pi though.

**Comment by devarshi** [comment]
> > so, I got Arlo (pro 2) integrated and working with homebridge-camera-ffmpeg. Just video streaming + snapshots for now, but it's a start.
> > https://github.com/devarshi/homebridge-camera-ffmpeg
> 
> Could you please post your config.json?

@meesjan  I have an example config in the readme in my repo.

**Comment by devarshi** [comment]
> I also recently submitted a PR to support streaming (heavily based on FFmpeg too), it's pending incorporation into the main branch - you can check it out on the [streaming-pr branch](https://github.com/devbobo/homebridge-arlo/tree/streaming-pr) or on [my fork](https://github.com/cbpowell/homebridge-arlo).
> 
> More testing always helps if you guys want to try it out! You do need a fairly specific FFmpeg if you're using a Raspberry Pi though.

@cbpowell that is neat! I found that with Arlo Pro 2, I didnt need to transcode video - you can just copy the video stream.. it saves processing power and starts faster. I didn’t experiment with the audio though - will check out your audio setup.

**Comment by cbpowell** [comment]
@devarshi Awesome! Yeah the video stream format (h264) is acceptable to HomeKit as long as it's the same size requested by the HomeKit device - this is typically 1280x720 which is what the Arlo streams out by default. But if you request the video via an Apple watch it requests a smaller video size, which does require transcoding.

**Comment by sdorilas** [comment]
I can't get streaming or snapshots to work. Weird part is video was working on 2 of my 4 cameras before I installed ffmpeg. Now nothing works at all. Snapshots are created when I first run homebridge though.
 I'm not sure how to configure the config file. I have 4 cameras, must I add each one and a source address?
}, {
 		"platform": "Camera-ffmpeg",
 		"cameras": [{
 			"name": "Camera Name",
 			"videoConfig": {
 				"source": "-re -i rtsp://myfancy_rtsp_stream",
 				"stillImageSource": "-i http://faster_still_image_grab_url/this_is_optional.jpg",
 				"maxStreams": 4,
 				"maxWidth": 1280,
 				"maxHeight": 720,
 				"maxFPS": 30
 			}
 		}]
 	}]
 }

**Comment by Rithord** [comment]
Hi @devarshi I was wondering if you were able to advise me on this error that I am getting when tapping on the video steam on the Home app

Unable to find suitable output format ‘arlo’ Invalid argument : Arlo

**Comment by devarshi** [comment]
> Hi @devarshi I was wondering if you were able to advise me on this error that I am getting when tapping on the video steam on the Home app
> 
> Unable to find suitable output format ‘arlo’ Invalid argument : Arlo

@sdorilas  @Rithord are you using the streaming-pr branch on this repo (that is @cbpowell ’s mod) or my repo (the homebridge-camera-ffmpeg mod)? Both take slightly different approaches to adding streaming, and the add-on and configuration are different between the two.

**Comment by sdorilas** [comment]
@devarshi  Thank you for getting back to me. I’m using the ffmpeg mod as far as I know

**Comment by Rithord** [comment]
@devarshi I tried using your repo to begin with after installing Jeffrey’s library and seemed to produce the error I mentioned so I tried going with Cbpowell’s method and when I restart homebridge with the new configuration for his repo I don’t see anything appear as I try to add the accessory, I believe I may have installed FFmpeg incorrectly for your repo, is there a guide you can advise on how to install it to suit your repo? 

Thanks in advance for all the help, I just bought the Arlo 2 pro 3 camera system a couple of days ago

**Comment by devarshi** [comment]
> @devarshi Thank you for getting back to me. I’m using the ffmpeg mod as far as I know Sent from my iPhone.
> […](#)

@sdorilas if you are using my ffmpeg mod, see here for the configuration example : 
https://github.com/devarshi/homebridge-camera-ffmpeg#using-arlo-cameras

In it's current form, you'll need to create multiple cameras as below (I know, pain. Planning a rewrite once I have some time on my hands :)):
```
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "Camera Name 1",
      "videoConfig": {
       "source": "arlo",
        .....
        "arloCameraIndex": "0"
      }
    },
    {
      "name": "Camera Name 2",
      "videoConfig": {
       "source": "arlo",
       .....
        "arloCameraIndex": "1"
      }
    },
  ]
}
```

**Comment by sdorilas** [comment]
{
 		"platform": "Camera-ffmpeg",
 		"cameras": [{
 			"name": "Living Room",
 			"videoConfig": {
 				"source": "arlo",
 				"maxStreams": 2,
 				"maxWidth": 1280,
 				"maxHeight": 720,
 				"maxFPS": 10,
 				"maxBitrate": 300,
 				"vcodec": "copy",
 				"audio": false,
 				"debug": true,
 				"arloUserName": "MY_EMAIL",
 				"arloPassword": "MY_PASS",
 				"arloCameraIndex": "0"
 			}

This is what I was using. So replace it with the one above, and list each camera individually?

**Comment by devarshi** [comment]
> @devarshi I tried using your repo to begin with after installing Jeffrey’s library and seemed to produce the error I mentioned so I tried going with Cbpowell’s method and when I restart homebridge with the new configuration for his repo I don’t see anything appear as I try to add the accessory, I believe I may have installed FFmpeg incorrectly for your repo, is there a guide you can advise on how to install it to suit your repo?
> 
> Thanks in advance for all the help, I just bought the Arlo 2 pro 3 camera system a couple of days ago

@Rithord If you installed ffmpeg following cbpowell's instructions, that should work just fine. Can you post your config here ? The error `Unable to find suitable output format ‘arlo’` seems like you may be using the config format from my mod with another plugin. 

Also, FYI, I've got both installed, and am seeing 2 things : 
1) With my ffmpeg mod, I reliably get snapshots. Video streaming also works most of the time and starts quickly (10-15seconds), but no audio.
2) With homebridge-arlo + cbpowell's changes, snapshots stop refreshing after a while (this seems to be a known issue), but video streaming tends to take a while to startup (30s-1min).

**Comment by devarshi** [comment]
> {
> "platform": "Camera-ffmpeg",
> "cameras": [{
> "name": "Living Room",
> "videoConfig": {
> "source": "arlo",
> "maxStreams": 2,
> "maxWidth": 1280,
> "maxHeight": 720,
> "maxFPS": 10,
> "maxBitrate": 300,
> "vcodec": "copy",
> "audio": false,
> "debug": true,
> "arloUserName": "MY_EMAIL",
> "arloPassword": "MY_PASS",
> "arloCameraIndex": "0"
> }
> 
> This is what I was using. So replace it with the one above, and list each camera individually?

Yup just replicate your config and increment the camera index.

**Comment by sdorilas** [comment]
Same error no matter what. It captures the initial snapshot then I get a cannot connect to camera issue This breaks my heart cuz at one point it was kind of working. I do thank you for all your help and patience 

[2018-11-8 14:01:28] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 46 secs
[2018-11-8 14:01:30] [Camera-ffmpeg] Start streaming video from Garage with 1280x720@299kBit
ffmpeg arlo -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 16533012 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XEwSdfJcwx7tkpzVd+PwC5EeOjw5ej5pvDw4h1WJ srtp://192.168.1.85:63176?rtcpport=63176&localrtcpport=63176&pkt_size=1316
ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma

  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100

[NULL @ 0x7fd7ce800000] Unable to find a suitable output format for 'arlo'
arlo: Invalid argument

[2018-11-8 14:01:30] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

**Comment by devarshi** [comment]
> Same error no matter what. It captures the initial snapshot then I get a cannot connect to camera issue This breaks my heart cuz at one point it was kind of working. I do thank you for all your help and patience

> [2018-11-8 14:01:30] [Camera-ffmpeg] Start streaming video from Garage with 1280x720@299kBit
> ffmpeg arlo -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 16533012 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XEwSdfJcwx7tkpzVd+PwC5EeOjw5ej5pvDw4h1WJ srtp://192.168.1.85:63176?rtcpport=63176&localrtcpport=63176&pkt_size=1316
> ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
> built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
> configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
> 
> libavutil 56. 14.100 / 56. 14.100
> libavcodec 58. 18.100 / 58. 18.100
> libavformat 58. 12.100 / 58. 12.100
> libavdevice 58. 3.100 / 58. 3.100
> libavfilter 7. 16.100 / 7. 16.100
> libavresample 4. 0. 0 / 4. 0. 0
> libswscale 5. 1.100 / 5. 1.100
> libswresample 3. 1.100 / 3. 1.100
> libpostproc 55. 1.100 / 55. 1.100
> 
> [NULL @ 0x7fd7ce800000] Unable to find a suitable output format for 'arlo'
> arlo: Invalid argument
> 
> [2018-11-8 14:01:30] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1

Ah - looks like Camera-ffmpeg module you are using is not the one with my changes (hence doesn't recognize the `arlo` option). try installing from here again : https://github.com/devarshi/homebridge-camera-ffmpeg/

**Comment by sdorilas** [comment]
installed it:
+ homebridge-camera-ffmpeg@0.1.8
added 2 packages from 3 contributors, removed 1 package and updated 6 packages in 21.444s

2018-11-8 14:17:05] [Harmony Hub] Fetching Logitech Harmony activities...
[2018-11-8 14:17:06] [Arlo] Online: Base Station Office [48946C72AAC64]
[2018-11-8 14:17:06] [Arlo] Found: Camera - Driveway [4N71697P26213]
[2018-11-8 14:17:07] [Arlo] Found: Camera - Inside [4WA16C7TCADF7]
[2018-11-8 14:17:07] [Arlo] Found: Camera - Backyard [4WA16C7VCFC4E]
[2018-11-8 14:17:07] [Arlo] Found: Camera - Driveway [4WA16C7YCB118]
[2018-11-8 14:17:07] 4N71697P26213 is running on port 53919.
[2018-11-8 14:17:07] 4WA16C7TCADF7 is running on port 53920.
[2018-11-8 14:17:07] 4WA16C7VCFC4E is running on port 53921.
[2018-11-8 14:17:07] 4WA16C7YCB118 is running on port 53922.

[2018-11-8 14:17:09] [Arlo] Online: Camera 4WA16C7YCB118 [4WA16C7YCB118]
[2018-11-8 14:17:10] [Arlo] Online: Camera 4WA16C7TCADF7 [4WA16C7TCADF7]
[2018-11-8 14:17:10] [Arlo] Online: Camera 4N71697P26213 [4N71697P26213]
[2018-11-8 14:17:10] [Arlo] Online: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E]
[2018-11-8 14:17:10] [Arlo] Online: Camera 4WA16C7TCADF7 [4WA16C7TCADF7]
[2018-11-8 14:17:10] [Arlo] Online: Camera 4WA16C7YCB118 [4WA16C7YCB118]
[2018-11-8 14:17:17] [LiftMaster2] Adding Device: "Garage Door Opener" - Device ID: 1700101613 (Gateway: "Home" - Gateway ID: 9590462)
[2018-11-8 14:17:17] [LiftMaster2] Garage Door Opener is closed.
[2018-11-8 14:17:22] [Arlo] Snapshot request: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E]
[2018-11-8 14:17:22] [Camera-ffmpeg] Snapshot from Garage at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:22] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:23] [Arlo] Snapshot confirmed: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E]
[2018-11-8 14:17:27] [Arlo] Snapshot downloaded: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E]
[2018-11-8 14:17:27] [Arlo] prepareStream
[2018-11-8 14:17:38] [Arlo] handleStreamRequest
[2018-11-8 14:17:40] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 282 secs
[2018-11-8 14:17:40] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:40] [Camera-ffmpeg] Snapshot from Garage at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:42] [Arlo] Snapshot request: Camera 4N71697P26213 [4N71697P26213]
[2018-11-8 14:17:43] [Arlo] Snapshot confirmed: Camera 4N71697P26213 [4N71697P26213]
[2018-11-8 14:17:44] [Camera-ffmpeg] Start streaming video from Backyard with 1280x720@299kBit
ffmpeg arlo -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 13667146 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 1GhXkd8ZWj3aC6OprBG0lkcj6BhItgnjfs3lqsI7 srtp://192.168.1.85:63179?rtcpport=63179&localrtcpport=63179&pkt_size=1316
ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma

  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100

[NULL @ 0x7fc752800000] Unable to find a suitable output format for 'arlo'

arlo: Invalid argument

[2018-11-8 14:17:45] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
[2018-11-8 14:17:47] [Arlo] Snapshot downloaded: Camera 4N71697P26213 [4N71697P26213]
[2018-11-8 14:17:50] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 272 secs
[2018-11-8 14:17:50] [Camera-ffmpeg] Snapshot from Garage at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:50] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:52] [Camera-ffmpeg] Start streaming video from Garage with 1280x720@299kBit
ffmpeg arlo -map 0:0 -vcodec copy -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 16030660 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params YGwOV9LPRttmAzndht5lfOsgyRmgjkiE7775Fllk srtp://192.168.1.85:49961?rtcpport=49961&localrtcpport=49961&pkt_size=1316
ffmpeg version 4.0.1
 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100

[NULL @ 0x7fa590000000] Unable to find a suitable output format for 'arlo'
arlo: Invalid argument

[2018-11-8 14:17:52] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1
[2018-11-8 14:17:56] [Arlo] Snapshot skipped: Camera 4WA16C7VCFC4E [4WA16C7VCFC4E] - Next in 267 secs
[2018-11-8 14:17:56] [Camera-ffmpeg] Snapshot from Garage at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:56] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:57] [Camera-ffmpeg] Snapshot from Living Room at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:17:57] [Arlo] Snapshot skipped: Camera 4N71697P26213 [4N71697P26213] - Next in 285 secs
[2018-11-8 14:17:58] [Arlo] prepareStream
[2018-11-8 14:18:08] [Arlo] handleStreamRequest
[2018-11-8 14:18:11] [Arlo] Snapshot skipped: Camera 4N71697P26213 [4N71697P26213] - Next in 271 secs
[2018-11-8 14:18:11] [Camera-ffmpeg] Snapshot from Garage at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:18:11] [Camera-ffmpeg] Snapshot from Living Room at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:18:11] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:18:12] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -
[2018-11-8 14:18:12] [Camera-ffmpeg] Snapshot from Backyard at 480x270
ffmpeg arlo -t 1 -s 480x270 -f image2 -

**Comment by Rithord** [comment]
Hi @devarshi this is my config file, I have both plugins installed and appear to get the same error no matter which one I try to change to, do you think this is something to do with FFmpeg and the original install? Is there some specific codecs that need to be installed or does FFmpeg installation take care of everything? It seems that @sdorilas and I are experiencing the same thing

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "restart": "sudo -n systemctl restart homebridge",
            "log": "systemd",
            "port": 8080,
            "sudo": true
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Living Room",
                    "videoConfig": {
                        "source": "arlo",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "copy",
                        "audio": false,
                        "debug": true,
                        "arloUserName": "username",
                        "arloPassword": "password",
                        "arloCameraIndex": "0"
                    }
                }
            ]
        }
    ],
    "accessories": [
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "Lamp",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff1/RESULT",
                "statusSet": "cmnd/sonoff1/POWER",
                "stateGet": "tele/sonoff1/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "TV Lights",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff2/RESULT",
                "statusSet": "cmnd/sonoff2/POWER",
                "stateGet": "tele/sonoff2/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "Desk Lights",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff3/RESULT",
                "statusSet": "cmnd/sonoff3/POWER",
                "stateGet": "tele/sonoff3/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "Lamp",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff4/RESULT",
                "statusSet": "cmnd/sonoff4/POWER",
                "stateGet": "tele/sonoff4/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "Lamp",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff5/RESULT",
                "statusSet": "cmnd/sonoff5/POWER",
                "stateGet": "tele/sonoff5/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "mqtt-switch-tasmota",
            "switchType": "outlet",
            "name": "Spare Switch",
            "url": "mqtt://192.168.1.54",
            "username": "username",
            "password": "password",
            "topics": {
                "statusGet": "stat/sonoff6/RESULT",
                "statusSet": "cmnd/sonoff6/POWER",
                "stateGet": "tele/sonoff6/STATE"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "activityTopic": "tele/sonoff/LWT",
            "activityParameter": "Online",
            "startCmd": "cmnd/sonoff/TelePeriod",
            "startParameter": "60",
            "manufacturer": "ITEAD",
            "model": "Sonoff",
            "serialNumberMAC": "00-00-00-00-00-00"
        },
        {
            "accessory": "RaspberryPiTemperature",
            "name": "RaspberryPi CPU Temperature"
        }
    ]
}

**Comment by sdorilas** [comment]
Hey @Rithord were you able to make any progress? Even my snapshots are no longer working now.

**Comment by Phoenix-DH** [comment]
I am still very interrested in getting this snapshot and livevideo working.
Maybe somebody who has everything up and running well post all the steps he did and which forks of homebridge-arlo and ffmpeg he has installed?

Would be great, Iam using raspi 2 and ARLO Pro.

**Comment by devarshi** [comment]
Sorry for the delayed responses folks.. @sdorilas @Rithord your configs seem correct. I think what you are missing is the correct `homebridge-camera-ffmpeg`. Can you follow instructions here ( https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/210#issuecomment-438802618 ) to see if you have it right (suggest removing any existing homebridge-camera-ffmpeg installs first) ? 

Also, it's probably a good idea to take the conversation around the `homebridge-camera-ffmpeg` module to that repo so we don't end up confusing folks here who are actually using `homebridge-arlo`. 

@Phoenix-DH I have both working, but with these limitations : https://github.com/devbobo/homebridge-arlo/issues/8#issuecomment-437109646. 
The ffmpeg install instructions from cbpowell ( https://github.com/cbpowell/homebridge-arlo#streaming-with-a-raspberry-pi-3 ) will work with both `homebridge-camera-ffmpeg` and `homebridge-arlo`.

**Comment by Kazom** [comment]
I know this thread is really old but has anyone started messing with HomeKit secure video support in Arlo? They added HomeKit support but left out that part. These are the only homebridge people I found working on secure video with their plugins: https://github.com/KhaosT/HAP-NodeJS/issues/741

Tagging you too incase this thread has notifications off from it being old.
@devarshi @Rithord @devbobo @cbpowell
