### ISSUE TITLE
Essential Camera

### ISSUE THREAD

**Issue by donavanbecker** [homebridge-plugins/homebridge-arlo#88]
Not able to stream

**Describe The Bug:** Snapshots come in but when you try to view the video it goes to not responding after a few minutes of loading.

**To Reproduce:** Try to Stream.

**Expected behavior:** Video Should Stream.

**Homebridge Config:**

```json
{
            "name": "Arlo",
            "email": "**************",
            "password": "**************",
            "include_cameras": true,
            "streaming": {
                "videoProcessor": "ffmpeg",
                "videoDecoder": "libx264",
                "videoEncoder": "libx264",
                "audioEncoder": "libopus",
                "packetSize": "1316",
                "maxBitrate": "300"
            },
            "platform": "Arlo"
        }
```

**Environment:**

* **Node.js Version**: 14.7.0
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.2.0-beta.34
* **Homebridge Arlo Version**: 2.1.0
* **Homebridge Config UI X Plugin Version**: 4.25.1-test.5
* **Operating System**:  macOS

**Comment by SmolSoftBoi** [comment]
@donavanbecker I'm trying to push my changes the `beta` branch, but nearly every file has a conflict, could you let me know what changes you've made?

**Comment by donavanbecker** [comment]
@EpicKris, I haven't really did much except for formatting. if you want delete beta branch you are more then welcome. then it will pull all your new changes.
