### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by RealDeemer** [homebridge-plugins/homebridge-arlo#9]
After installing ARLO and getting homebridge to the latest version I am getting an issue. The system finally does not start. Is there anything I can do?

```
[2017-12-22 15:53:42] [Arlo] Initializing Arlo platform...
[2017-12-22 15:53:42] Loading 0 accessories...
Setup Payload:
X-HM://0023HR5****
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
 <...>
[2017-12-22 15:53:42] Homebridge is running on port 51826.
[2017-12-22 15:53:45] [Arlo] Found: Camera - 4N727******** [4N727********]
[2017-12-22 15:53:45] [Arlo] _createStreamControllers
/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:268
        body[Constants.TO]   = device.id;
                                     ^

TypeError: Cannot read property 'id' of undefined
    at Arlo.notify (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:268:38)
    at ArloCamera.get (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:23:21)
    at new ArloCameraAccessory (/usr/lib/node_modules/homebridge-arlo/index.js:244:21)
    at ArloPlatform.addAccessory (/usr/lib/node_modules/homebridge-arlo/index.js:82:48)
    at ArloPlatform.<anonymous> (/usr/lib/node_modules/homebridge-arlo/index.js:100:26)
    at emitOne (events.js:96:13)
    at Arlo.emit (events.js:188:7)
    at Arlo.<anonymous> (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:47:26)
    at Request._callback (/usr/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:280:21)
    at Request.self.callback (/usr/lib/node_modules/homebridge-arlo/node_modules/request/request.js:186:22)
```

**Comment by keithws** [comment]
I just updated from 0.0.1 to 0.0.2 and I am getting the same error.

**Comment by rwfisheriv** [comment]
Getting the same error here.

**Comment by yelef77** [comment]
same error for me

**Comment by devbobo** [comment]
I'm hoping that version `0.0.3` should address this issue, please give it a go.

**Comment by eduardoboucas** [comment]
I’ve just installed the plugin for the first time and I’m seeing this. Any tips on how to fix it? Thanks.

**Comment by michaelkedwards** [comment]
I’ve also just installed the plugin and I’m seeing this same problem. Would love to get this to work...thanks

**Comment by michaelkedwards** [comment]
I found out that I had an out dated homebridge-nest which I'm also running so once I updated that the error went away. Hope this help someone else. All your plugins need to be updated if you update version of homebridge (only makes sense now).

**Comment by bobjoylove** [comment]
I'm having this issue too.  Homebridge is updated.  Latest version of Homebridge-Arlo.

>  homebridge
> [2018-12-27 18:22:10] Loaded config.json with 0 accessories and 1 platforms.
> [2018-12-27 18:22:10] ---
> [2018-12-27 18:22:11] Loaded plugin: homebridge-arlo
> [2018-12-27 18:22:11] Registering platform 'homebridge-arlo.Arlo'
> [2018-12-27 18:22:11] ---
> [2018-12-27 18:22:11] Loaded plugin: homebridge-legacy-plugins
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.AD2USB'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.Carwings'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.ELKM1'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.FileSensor'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HomeMatic'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.Tesla'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.X10'
> [2018-12-27 18:22:11] Registering accessory 'homebridge-legacy-plugins.mpdclient'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.Domoticz'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.HomeAssistant'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.HomeSeer'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.ISY'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.LIFx'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.SmartThings'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.TelldusLive'
> [2018-12-27 18:22:11] Registering platform 'homebridge-legacy-plugins.ZWayServer'
> [2018-12-27 18:22:11] ---
> [2018-12-27 18:22:12] Loaded plugin: homebridge-smartthings
> [2018-12-27 18:22:12] Registering platform 'homebridge-smartthings.SmartThings'
> [2018-12-27 18:22:12] ---
> [2018-12-27 18:22:13] Loaded plugin: homebridge-smartthings-routine
> [2018-12-27 18:22:13] Registering accessory 'homebridge-smartthings-routine.SmartThingsRoutine'
> [2018-12-27 18:22:13] ---
> [2018-12-27 18:22:13] Loaded plugin: homebridge-smartthings-routine-triggers
> [2018-12-27 18:22:13] Registering accessory 'homebridge-smartthings-routine-triggers.HomebridgeRoutineTrigger'
> [2018-12-27 18:22:13] ---
> [2018-12-27 18:22:13] Loaded plugin: homebridge-broadlink-rm
> [2018-12-27 18:22:13] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
> [2018-12-27 18:22:13] ---
> [2018-12-27 18:22:13] Loading 1 platforms...
> [2018-12-27 18:22:13] [Arlo] Initializing Arlo platform...
> Setup Payload:
> X-HM://0023ISYWYL98D
> Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
>                                                       
> Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
>                           
>                        
> [2018-12-27 18:22:14] Homebridge is running on port 51826.
> [2018-12-27 18:22:18] [Arlo] Online: Base Station Arlo Pro Base [****9ED]
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Garage 1 [****7A5]
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at new ArloCameraAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:285:21)
>     at ArloPlatform.addAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:84:48)
>     at ArloPlatform.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:135:26)
>     at Arlo.emit (events.js:160:13)
>     at Arlo.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
>     at Request._callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
>     at Request.self.callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:160:13)
> undefined
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Garage 2 [****634]
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at new ArloCameraAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:285:21)
>     at ArloPlatform.addAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:84:48)
>     at ArloPlatform.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:135:26)
>     at Arlo.emit (events.js:160:13)
>     at Arlo.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
>     at Request._callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
>     at Request.self.callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:160:13)
> undefined
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Front Door 1 [****E3F]
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at new ArloCameraAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:285:21)
>     at ArloPlatform.addAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:84:48)
>     at ArloPlatform.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:135:26)
>     at Arlo.emit (events.js:160:13)
>     at Arlo.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
>     at Request._callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
>     at Request.self.callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:160:13)
> undefined
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Back Garden 1 [****F6D]
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at new ArloCameraAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:285:21)
>     at ArloPlatform.addAccessory (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:84:48)
>     at ArloPlatform.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:135:26)
>     at Arlo.emit (events.js:160:13)
>     at Arlo.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:49:26)
>     at Request._callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:310:21)
>     at Request.self.callback (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:160:13)
> undefined
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Broken [****3E9]
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Garage Pro [****F53]
> [2018-12-27 18:22:18] [Arlo] Found: Camera - Arlo Patio Pro [****30F]
> [2018-12-27 18:22:18] ****7A5 is running on port 43773.
> [2018-12-27 18:22:18] ****634 is running on port 36281.
> [2018-12-27 18:22:18] ****E3F is running on port 35419.
> [2018-12-27 18:22:18] ****F6D is running on port 43087.
> [2018-12-27 18:22:18] ****3E9 is running on port 36523.
> [2018-12-27 18:22:18] ****F53 is running on port 45865.
> [2018-12-27 18:22:18] ****30F is running on port 33717.
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at ArloCameraAccessory.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:305:25)
>     at ontimeout (timers.js:458:11)
>     at tryOnTimeout (timers.js:296:5)
>     at Timer.listOnTimeout (timers.js:259:5)
> undefined
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at ArloCameraAccessory.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:305:25)
>     at ontimeout (timers.js:458:11)
>     at tryOnTimeout (timers.js:296:5)
>     at Timer.listOnTimeout (timers.js:259:5)
> undefined
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at ArloCameraAccessory.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:305:25)
>     at ontimeout (timers.js:458:11)
>     at tryOnTimeout (timers.js:296:5)
>     at Timer.listOnTimeout (timers.js:259:5)
> undefined
> TypeError: Cannot read property 'id' of undefined
>     at Arlo.notify (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/Arlo.js:293:43)
>     at ArloCamera.get (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/node_modules/node-arlo/lib/ArloCamera.js:24:21)
>     at ArloCameraAccessory.<anonymous> (/home/pi/.nvm/versions/node/v9.5.0/lib/node_modules/homebridge-arlo/index.js:305:25)
>     at ontimeout (timers.js:458:11)
>     at tryOnTimeout (timers.js:296:5)
>     at Timer.listOnTimeout (timers.js:259:5)
> undefined
> [2018-12-27 18:22:21] [Arlo] Online: Camera ****F53 [****F53]
> [2018-12-27 18:22:21] [Arlo] Online: Camera ****30F [****30F]
> [2018-12-27 18:22:21] [Arlo] Online: Camera ****30F [****30F]

**Comment by Djelibeybi** [comment]
I have the same issue. I have been bouncing around branches, between `master` and the `streaming-pr` branch, in case that helps. I've also reset my Arlo system and registered it to a different email.

**Comment by Djelibeybi** [comment]
Replying because I found the solution: ensure that the account that you use to connect to Arlo has admin access. :)
